spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  security:
    user:
      name: karthik
      password: karthik123
      

server:
    port: 9091    
    
info:
 application:
 name: User Registration Project
 
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
