spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
    port: 9091    
    
info:
 app:
 name: User Registration Project
 description: Checck User Details
 version : 1.0.0
 
management:
  endpoints:
    web:
      exposure:
        include: "*"